// <auto-generated />
using JaKleingartenParadies.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JaKleingartenParadies.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20230217141856_modelInit")]
    partial class modelInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("JaKleingartenParadies.DB.TestTable", b =>
                {
                    b.Property<long>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Test1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uid");

                    b.ToTable("TestTable");
                });
#pragma warning restore 612, 618
        }
    }
}
